window.Modal={open(id){document.getElementById(id).classList.remove("hidden")},close(id){document.getElementById(id).classList.add("hidden")}};
window.Page={init(){if(!Auth.requireAdmin())return;const cat=document.getElementById("book-category");cat.innerHTML=CATEGORIES.map(c=>`<option value="${c.id}">${c.name}</option>`).join("");let deleteId=null;
function render(){const q=document.getElementById("admin-book-search").value.toLowerCase();const list=BookService.all().filter(b=>`${b.title} ${b.author}`.toLowerCase().includes(q));document.getElementById("book-table").innerHTML=`<div class="admin-table-wrap"><table class="admin-table"><thead><tr><th>Sách</th><th>Tác giả</th><th>Thể loại</th><th>Năm</th><th>Đánh giá</th><th>Thao tác</th></tr></thead><tbody>${list.map(b=>`<tr><td><div style="display:flex;gap:10px;align-items:center"><img src="${b.cover}"><b>${b.title}</b></div></td><td>${b.author}</td><td>${Format.category(b.categoryId)}</td><td>${b.year}</td><td>⭐ ${b.rating}</td><td><button class="btn btn-light" data-edit="${b.id}">Sửa</button> <button class="btn btn-danger" data-delete="${b.id}">Xóa</button></td></tr>`).join("")}</tbody></table></div>`}
function openBook(id=null){const b=id?BookService.get(id):{id:"",title:"",author:"",categoryId:1,year:2026,cover:""};document.getElementById("book-id").value=b.id;document.getElementById("book-title").value=b.title;document.getElementById("book-author").value=b.author;document.getElementById("book-category").value=b.categoryId;document.getElementById("book-year").value=b.year;document.getElementById("book-cover").value=b.cover;document.getElementById("book-modal-title").textContent=id?"Sửa sách":"Thêm sách";Modal.open("book-modal")}
document.getElementById("add-book").onclick=()=>openBook();document.getElementById("admin-book-search").oninput=render;
document.addEventListener("click",e=>{if(e.target.dataset.edit)openBook(+e.target.dataset.edit);if(e.target.dataset.delete){deleteId=+e.target.dataset.delete;document.getElementById("delete-message").textContent=`Xóa sách "${BookService.get(deleteId)?.title}"?`;Modal.open("delete-modal")}});
document.getElementById("confirm-delete").onclick=()=>{BookService.remove(deleteId);Modal.close("delete-modal");Toast.show("Đã xóa sách");render()};
document.getElementById("save-book").onclick=()=>{const id=+document.getElementById("book-id").value||Date.now();BookService.save({id,title:document.getElementById("book-title").value.trim(),author:document.getElementById("book-author").value.trim(),categoryId:+document.getElementById("book-category").value,year:+document.getElementById("book-year").value,cover:document.getElementById("book-cover").value.trim()||"https://placehold.co/300x400?text=Book",rating:5,reviews:0,description:"Sách được quản lý trong thư viện LibHub.",content:"Nội dung mẫu của sách."});Modal.close("book-modal");Toast.show("Đã lưu sách");render()};render();
}};
