window.Modal={open(id){document.getElementById(id).classList.remove("hidden")},close(id){document.getElementById(id).classList.add("hidden")}};
window.Page={init(){if(!Auth.requireAdmin())return;let deleteId=null,resetId=null;
function render(){const q=document.getElementById("admin-user-search").value.toLowerCase();const list=UserService.all().filter(u=>`${u.username} ${u.fullName} ${u.email}`.toLowerCase().includes(q));document.getElementById("user-table").innerHTML=`<div class="admin-table-wrap"><table class="admin-table"><thead><tr><th>Người dùng</th><th>Email</th><th>Vai trò</th><th>Trạng thái</th><th>Thao tác</th></tr></thead><tbody>${list.map(u=>`<tr><td><div style="display:flex;align-items:center;gap:10px"><img src="${u.avatar}" style="width:40px;height:40px;border-radius:50%;object-fit:cover"><div><b>${u.fullName}</b><br><small>@${u.username}</small></div></div></td><td>${u.email}</td><td>${u.role}</td><td><span class="badge ${u.status==="active"?"badge-success":"badge-danger"}">${u.status==="active"?"Hoạt động":"Đã khóa"}</span></td><td><button class="btn btn-light" data-user-edit="${u.id}">Sửa</button> ${u.role!=="Admin"?`<button class="btn btn-light" data-reset="${u.id}">Reset MK</button><button class="btn btn-danger" data-user-delete="${u.id}">Xóa</button>`:""}</td></tr>`).join("")}</tbody></table></div>`}
function edit(id){const u=UserService.get(id);document.getElementById("user-id").value=u.id;document.getElementById("user-name").value=u.fullName;document.getElementById("user-email").value=u.email;document.getElementById("user-role").value=u.role;document.getElementById("user-status").value=u.status;Modal.open("user-modal")}
document.getElementById("admin-user-search").oninput=render;
document.addEventListener("click",e=>{if(e.target.dataset.userEdit)edit(+e.target.dataset.userEdit);if(e.target.dataset.userDelete){deleteId=+e.target.dataset.userDelete;document.getElementById("delete-message").textContent=`Xóa người dùng "${UserService.get(deleteId)?.fullName}"?`;Modal.open("delete-modal")}if(e.target.dataset.reset){resetId=+e.target.dataset.reset;Modal.open("reset-password-modal")}});
document.getElementById("confirm-delete").onclick=()=>{UserService.remove(deleteId);Modal.close("delete-modal");Toast.show("Đã xóa người dùng");render()};
document.getElementById("confirm-reset").onclick=()=>{Modal.close("reset-password-modal");Toast.show("Đã reset mật khẩu về mật khẩu mặc định")};
document.getElementById("save-user").onclick=()=>{const u=UserService.get(+document.getElementById("user-id").value);Object.assign(u,{fullName:document.getElementById("user-name").value,email:document.getElementById("user-email").value,role:document.getElementById("user-role").value,status:document.getElementById("user-status").value});UserService.save(u);if(u.id===Auth.current().id)Storage.set("current_user",u);Modal.close("user-modal");Toast.show("Đã cập nhật người dùng");render()};render();
}};
