window.Page={init(){
  const id=new URLSearchParams(location.search).get("id"), book=BookService.get(id);
  if(!book){document.querySelector(".detail").innerHTML='<div class="empty">Không tìm thấy sách.</div>';return}
  document.getElementById("detail-cover").innerHTML=`<div class="detail-cover"><img src="${book.cover}" alt="${book.title}" onerror="this.style.display='none'"></div>`;
  document.getElementById("book-detail-content").innerHTML=`<span class="badge badge-success">${Format.category(book.categoryId)}</span><h1 style="font-size:38px;margin:10px 0">${book.title}</h1><h3 style="font-weight:500;color:var(--muted)">${book.author}</h3><p style="margin:18px 0">${book.description}</p><p class="text-muted">Năm xuất bản: ${book.year}</p><div class="actions" style="margin-top:20px"><a class="btn btn-primary" href="reader.html?id=${book.id}">📖 Đọc sách</a><button id="fav" class="btn btn-light">♡ Yêu thích</button></div>`;
  document.getElementById("book-rating").innerHTML=`<div style="margin-top:20px"><span class="rating" style="font-size:22px">${Format.stars(book.rating)}</span> <strong>${book.rating}/5</strong> · ${book.reviews} đánh giá</div>`;
  function renderReviews(){const rs=ReviewService.byBook(book.id);document.getElementById("review-list").innerHTML=`<h3 style="margin-top:25px">Đánh giá (${rs.length})</h3>`+(rs.length?rs.map(r=>{const u=UserService.get(r.userId)||{fullName:"Độc giả",avatar:"https://i.pravatar.cc/50"};return `<div class="review"><div class="review-head"><img src="${u.avatar}"><strong>${u.fullName}</strong><span class="rating">${Format.stars(r.rating)}</span></div><p>${r.text}</p><small class="text-muted">${Format.date(r.date)}</small></div>`}).join(""):'<p class="text-muted" style="margin-top:12px">Chưa có đánh giá.</p>')}
  let fav=Storage.get("library_favorites",[]);const fb=document.getElementById("fav");function sync(){fb.textContent=fav.includes(book.id)?"♥ Đã yêu thích":"♡ Yêu thích"}sync();fb.onclick=()=>{fav=fav.includes(book.id)?fav.filter(x=>x!==book.id):[...fav,book.id];Storage.set("library_favorites",fav);sync();Toast.show("Đã cập nhật yêu thích")};
  document.getElementById("submit-review").onclick=()=>{const u=Auth.current();if(!u){Toast.show("Vui lòng đăng nhập","error");return}const text=document.getElementById("review-text").value.trim();if(!text)return Toast.show("Hãy nhập nội dung đánh giá","error");ReviewService.add({bookId:book.id,userId:u.id,rating:+document.getElementById("review-rating").value,text,date:new Date().toISOString()});document.getElementById("review-text").value="";renderReviews();Toast.show("Đã gửi đánh giá")};
  renderReviews();
}};
